# Generated by Django 5.0.7 on 2024-08-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processing', 'Processing'), ('Cleaned', 'Cleaned'), ('Annotated', 'Annotated'), ('Completed', 'Completed'), ('Error', 'Error')], default='Uploaded', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.text')),
            ],
        ),
        migrations.CreateModel(
            name='UnknownWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('is_typo', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('correct_form', models.CharField(blank=True, max_length=255, null=True)),
                ('positions', models.JSONField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.text')),
            ],
        ),
        migrations.CreateModel(
            name='UnknownWordBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Checked', 'Checked'), ('UpdatingApertium', 'Updating Apertium'), ('RebuildingApertium', 'Rebuilding Apertium'), ('Rechecking', 'Rechecking'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.text')),
                ('words', models.ManyToManyField(to='corpus.unknownword')),
            ],
        ),
        migrations.CreateModel(
            name='VersionedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('updated_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.text')),
            ],
        ),
    ]
